version: "3.9"
services:
  perf-pushgateway-service:
    image: prom/pushgateway
    ports:
      - 9091:9091
    networks:
      - web
  prometheus:
    image: prom/prometheus
    depends_on:
      - perf-pushgateway-service
    volumes:
      - ./prometheus:/etc/prometheus:ro
    networks:
      - web
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - web
networks:
  web:
    external: true
volumes:
  grafana_data:
